USE [djk_qg]
GO

/****** Object:  Table [dbo].[p_passpass]    Script Date: 2017/12/7 17:50:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[p_passpass](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[用户名] [nchar](20) NULL,
	[密码] [nchar](20) NULL,
 CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

